name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Geode CLI
        run: |
          Invoke-WebRequest -Uri "https://github.com/geode-sdk/cli/releases/latest/download/geode-windows.exe" -OutFile "geode.exe"
          mkdir C:\geode
          move geode.exe C:\geode\
          echo "C:\geode" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Setup Geode SDK
        run: |
          geode sdk install --yes
        shell: cmd

      - name: Build
        run: |
          geode build
        shell: cmd

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Fembot-Mod
          path: build/*.geode