name: Build Geode Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Geode
        run: |
          curl -L -o geode.exe https://github.com/geode-sdk/cli/releases/latest/download/geode-windows.exe
          geode.exe sdk install --yes
        shell: cmd

      - name: Build
        run: geode build
        shell: cmd

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Fembot-Mod
          path: build/*.geode