name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja manually
        run: |
          curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/latest/download/ninja-win.zip
          7z x ninja.zip -oC:\ninja
          echo "C:\ninja" >> $env:GITHUB_PATH
        shell: pwsh

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          sdk: 'latest'

      - name: Upload the built mod
        uses: actions/upload-artifact@v4
        with:
          name: Fembot-Mod
          path: ${{ steps.build.outputs.build-output }}